[workspace]
authors = ["Alexey Shiklomanov <alexey.shiklomanov@gmail.com>"]
channels = ["conda-forge"]
name = "cimis-to-irrigation"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
r = ">=4.5,<4.6"
r-terra = ">=1.8_93,<2"
r-sf = ">=1.0_24,<2"
gdal = ">=3.12.1,<4"
r-arrow = ">=22.0.0,<23"
r-dplyr = ">=1.2.0,<2"
r-targets = ">=1.11.4,<2"
r-crew = ">=1.3.0,<2"
r-units = ">=1.0_0,<2"
libgdal-hdf5 = ">=3.12.1,<4"
r-qs2 = ">=0.1.7,<0.2"
r-readr = ">=2.1.4,<3"
r-purrr = ">=1.0.2,<2"
r-glue = ">=1.7.1,<2"
r-httr2 = ">=1.2.2,<2"
r-ggplot2 = ">=4.0.2,<5"
r-tidyr = ">=1.3.2,<2"
r-jsonlite = ">=2.0.0,<3"
